### ISSUE TITLE
Fix bullet point formatting on blog posts

### ISSUE THREAD

**Issue by leviem1** [sebs-scholarship/Theme#20]
The formatting of bullet points on blog posts is pretty ugly. Let's try to fix it.

[Example](https://test.blog.sebsscholarship.org/2021/03/08/the-first-thing-you-should-do-with-your-roommate.html)

See this [article](https://stackoverflow.com/questions/28977320/how-do-i-get-the-bullet-points-of-a-ul-to-center-with-the-text).

**Comment by hansajeejasinghe** [comment]
I would like to contribute, Can you please assign me to this.

**Comment by leviem1** [comment]
Hello @hansajeejasinghe, I unfortunately handed this over to @DallasMusso yesterday. Also, contributions to this repository require a signed copyright agreement at this time due to the use of copyrighted assets in our code. I'll keep you in mind for future changes and will consider adding a LICENSE file to this repo

**Comment by hansajeejasinghe** [comment]
Oh, I see. Thank you.
